### PR TITLE
initial commit, working on templates for ceph ansible

### PR DESCRIPTION
**Pull request by ericlake**

### CODE REVIEW

**Comment by ericlake** [comment]
Still needed:

- Update the README
- Update the metadata

**Comment by ericlake** [comment]
Found a couple of issues when testing on site. I am going to be pushing an update soon.

**Comment by ericlake** [comment]
I think that this is ready for a review. The only thing that I think that it could be missing is providing the /etc/ansible/hosts file.

**Comment by jmrickard** [comment]
Eric, 
I tested the role and it works after I configured the following:
- commented out repo task import (not needed for me)
- In vars/main i added public and cluster nets
- Added the block below into main task file to create keys directory for Ceph as defined under defaults.

- name: Create ceph fetch directory
  file:
    state: directory
    path: "{{ ansible_keys_dir }}"
    owner: root
    group: root
    mode: 0644

**Comment by jmrickard** [comment]
Eric - tested changes and everything looks good to go.

**Pull request merged**
